remote_theme: samarsault/plainwhite-jekyll

title: for NGINX Controller
author: DDDAONG
email: your-email@domain.com
#description: > # this means to ignore newlines until "show_exerpts:"
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
show_excerpts: true # set to true to show excerpts on the homepage

plainwhite:
  name: dddaong
  tagline: |
    Network Eng.
    Newbie in github
  date_format: "%Y-%m-%d"
  social_links:
    #twitter: Don'tHave
    github: dddaong/APIM
    #linkedIn: Don'tHave
    #rss: rss
    #dribbble: Don'tHave
    #flickr:   Don'tHave
    #instagram: Don'tHave
    #pinterest: Don'tHave
    #youtube: Don'tHave
    #facebook: Don'tHave
    #soundcloud: Don'tHave
    #telegram: Don'tHave
    #gitlab: Don'tHave
    #email: Don'tHave

  navigation:
    - title: Administrate BIG-IP
      url: "/bigip"
      #url: "https://dddaong.github.io/bigip/"
    - title: NGINX+ Ingress Controller
      url: "https://dddaong.github.io/"
    - title: NGINX Controller + APIM
      url: "https://dddaong.github.io/APIM/"

  search: true
  sitemap: true
  portfolio_image:      "assets/portfolio.png"
  html_lang: "kr"
  dark_mode: true
  disqus_shortname: https-dddaong-github-io

plugins:
  - jekyll-seo-tag
